name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'ravikumara004/protectbranch'
        submodules: 'recursive'
        token: ${{ secrets.MY_TOKEN }}
        path: 'protectbranch'  # Optional: directory to checkout the repository
        ref: 'main'  # Specify the branch name here
 
